config/routes.rb
Rails.application.routes.draw do
  resources :to_dos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/to_do.rb
class ToDo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  after_action :add_csrf_token

  private

  def add_csrf_token
    cookies["XSRF-TOKEN"] = form_authenticity_token
  end
end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController
  before_action :set_to_do, only: %i[show edit update destroy]

  # GET /to_dos
  # GET /to_dos.json
  def index
    render inertia: "ToDoApp", props: { toDoItems: ToDo.all }
  end

  # POST /to_dos
  # POST /to_dos.json
  def create
    to_do = ToDo.new(to_do_params)

    if to_do.save
      redirect_to to_dos_path, notice: "To do was successfully created."
    else
      render inertia: "ToDoApp", props: { toDoItems: ToDo.all, errors: true }
    end
  end

  def update
    if @to_do.update(to_do_params)
      redirect_to to_dos_path, notice: "To do was successfully updated."
    else
      render inertia: "ToDoApp", props: { toDoItems: ToDo.all, errors: @to_do.errors }
    end
  end

  # DELETE /to_dos/1
  # DELETE /to_dos/1.json
  def destroy
    @to_do.destroy
    head :no_content
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_to_do
    @to_do = ToDo.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def to_do_params
    params.require(:to_do).permit(:description, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/to_dos_helper.rb
module ToDosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InertiaTodo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'index' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/to_dos/_form.html.erb
<%= form_with(model: to_do, local: true) do |form| %>
  <% if to_do.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(to_do.errors.count, "error") %> prohibited this to_do from being saved:</h2>

      <ul>
        <% to_do.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/to_dos/edit.html.erb
<h1>Editing To Do</h1>

<%= render 'form', to_do: @to_do %>

<%= link_to 'Show', @to_do %> |
<%= link_to 'Back', to_dos_path %>

app/views/to_dos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>To Dos</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @to_dos.each do |to_do| %>
      <tr>
        <td><%= to_do.description %></td>
        <td><%= to_do.completed %></td>
        <td><%= link_to 'Show', to_do %></td>
        <td><%= link_to 'Edit', edit_to_do_path(to_do) %></td>
        <td><%= link_to 'Destroy', to_do, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New To Do', new_to_do_path %>

app/views/to_dos/new.html.erb
<h1>New To Do</h1>

<%= render 'form', to_do: @to_do %>

<%= link_to 'Back', to_dos_path %>

app/views/to_dos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @to_do.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @to_do.completed %>
</p>

<%= link_to 'Edit', edit_to_do_path(@to_do) %> |
<%= link_to 'Back', to_dos_path %>